### ISSUE TITLE
build.bat Not Compiling

### ISSUE THREAD

**Issue by Nascarfast48** [Not-So-Filter/s1-proto-disasm#1]
build.bat Isn't compiling the stuff into a proper "s1bult.bin" file like it should be. It'll appear for about 5 seconds then disappear.

**Comment by Totally-Not-Filter** [comment]
What OS are you using for building? I'm assuming you are using Windows, correct?

**Comment by Totally-Not-Filter** [comment]
This is outdated, building works fine.
