### ISSUE TITLE
Where the tiles and enemys?

### ISSUE THREAD

**Issue by SonicSuperFan** [Not-So-Filter/s1-proto-disasm#2]
i loaded it in and it didnt show anything!
![image_2024-08-03_182536212](https://github.com/user-attachments/assets/2b352da0-9ed7-4e16-b891-c3d4d350b128)

**Comment by SonicSuperFan** [comment]
doesnt even load on the emulator!

**Comment by Totally-Not-Filter** [comment]
@SonicSuperFan Oops, I forgot to edit SonLVL's ini file. I'll get to fixing it soon though, so don't worry.

**Comment by SonicSuperFan** [comment]
> @SonicSuperFan Oops, I forgot to edit SonLVL's ini file. I'll get to fixing it soon though, so don't worry.

just a question but when is soon?

**Comment by Totally-Not-Filter** [comment]
> > @SonicSuperFan Oops, I forgot to edit SonLVL's ini file. I'll get to fixing it soon though, so don't worry.
> 
> just a question but when is soon?

Soon will probably by the end of this month, or sooner. Currently working on fixing 74kb worth of errors with compiling.

**Comment by Totally-Not-Filter** [comment]
Has been fixed as of now.
